{
 "title": "Data quality",
 "time": { "from": "2022-02-01T00:00:00.000Z", "to": "2022-02-06T00:00:00.000Z" },
 "panels": [
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Drift columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction shift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}