source_stream_name = "stg_ride_events_r"
output_stream_name = "stg_ride_predictions_r"
model_bucket = "stg-mlflow-models-code-owners-r"
lambda_function_local_path = "../lambda_function.py"
docker_image_local_path = "../Dockerfile"
ecr_repo_name = "stg_stream_model_duration_r"
lambda_function_name = "stg_prediction_lambda_r"
